#连接参数
address: 127.0.0.1
port: 8090

#进程ID保存文件
pidfile: ./httpserver.pid

#并行线程数
procss: 0

#连接有效时间
#时间单位为秒
request_read_buffer: 512
life_time: 10

#CGI连接设置
php_cgi: ['127.0.0.1:9000']

webs:
  web1:
    web_root: G:\code\godoc
    host: www.zb.com
    default: index.html,index.php
    router: {
      .*\.php$: {
        pass: php_cgi,
     },
     .*: {
        etag: on,
        expires: 60
     }
    }