#连接参数
address: 127.0.0.1
port: 8090

#进程ID保存文件
pidfile: ./httpserver.pid

#并行线程数
procss: 0

#连接有效时间
#时间单位为秒
request_read_buffer: 512
life_time: 10

#CGI连接设置
php_cgi: ['127.0.0.1:9000']

# 虚拟主机列表配置
# 因为是个列表，所以用 "-", 同样的，内部的路由规则为规则列表，所以也用 "-", 个人理解
vhosts:
    - web_root: G:\code\godoc
      host: www.haha.fuck
      router:
          - pattern: .*\.php$
            rules:
                - pass: php_cgi
                  expires: 60
          - pattern: .*
            rules:
                - etag: on
                  expires: 60

    - web_root: G:\code\godoc
      host: www.haha.fuck
      router:
          - pattern: .*\.php$
            rules:
                - pass: php_cgi
                  expires: 60
          - pattern: .*
            rules:
                - etag: on
                  expires: 60

webs:
  - web_root: G:\code\godoc
    host: www.zb.com
    default: index.html,index.php
    router: {
      .*\.php$: {
        pass: php_cgi,
     },
     .*: {
        etag: on,
        expires: 60
     }
    }